### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by limelect** [Real-hackbard/Explorer#1]
Just for testing I added
const
  ViewStyle : Array[0..4] of TViewStyle = (vsSmallIcon, vsIcon, vsList, vsReport,vsReport) ;
why becouse you have 5 positions not 4 as you have a line in the menue.
Other wise you have Huge error.
I hop you understand
Press detail and you will see

Further more one more bug
In listview
Under the debuger press  with **computers** press any disk >>>>>>>> Error
**List index out of  bound**

Ok I found the error
  StatusBar1.Panels[0].Text := ListView1.Selected.SubItems.Strings[0] + ' | ' +
                                 ListView1.Selected.SubItems.Strings[1] + ' | ' +
                                 ListView1.Selected.SubItems.Strings[2];<<<<<<<<<<<<< does not exist under above conditions

**Comment by Real-hackbard** [comment]
Thanks for the message.

I think I understand the problem now.

You can take some steps to prevent the errors.

1: if ListView1.Selected = nil then Exit;   // To prevent the error.
2 : Or add another panel to the status bar if needed.
3: The program includes...

```
procedure TForm1.SelectStyle(Sender: TObject);
const
  ViewStyle : Array[0..3] of TViewStyle = (vsSmallIcon, vsIcon, vsList, vsReport) ;
begin
  ListView1.ViewStyle := ViewStyle[(Sender as TMenuItem).MenuIndex] ;
  (Sender as TMenuItem).Checked := True ;
end;
```

...but you can also change the style directly with...

  ```
  ListView1.ViewStyle := vsIcon;
  ListView1.ViewStyle := vsReport;
  ListView1.ViewStyle := vsList;
  ListView1.ViewStyle := vsSmallIcon;
```

Hope this helps, happy coding.

**Comment by limelect** [comment]
I am a 30-year professional Delphi. You need to fix your bugs. I do not

**Comment by Real-hackbard** [comment]
Okay, I've fixed the errors for now, thanks again for the heads-up.

Menu details couldn't be found because of the separator line in the menu.

Missing status bar panel added.

I'm working on too many projects, so mistakes happen.

**Comment by limelect** [comment]
You still have a problem

<img width="744" height="487" alt="Image" src="https://github.com/user-attachments/assets/24920267-1037-46e9-9800-c07472d5bd50" />

**Comment by Real-hackbard** [comment]
The exception error was triggered by the absence of data in all ListViewSubitems.

As soon as there is no data in the subitems, access to the items must be blocked.

I've improved it again and tested it with all hard drives and removable media; it should now be exception error-free.

The same problem was also in the context menu.

**Comment by limelect** [comment]
Open computer
**It is about time I will stop playing with your software**  this is not serious programing

Did nothing else  TE ???? in explorer field

<img width="492" height="160" alt="Image" src="https://github.com/user-attachments/assets/88d97384-adac-411a-9650-bb7f7c7982b6" />

Also NEW>Textdocument

<img width="977" height="422" alt="Image" src="https://github.com/user-attachments/assets/4f44f1dc-74fe-47ee-8d00-b9f9ecef444e" />

Good luck 
See my site specialy the free programs
limelect.com
and again have good luck

**Comment by Real-hackbard** [comment]
Sorry it didn't help you.

Thanks anyway for your help; I'll continue working with Explorer.

I wish you continued success as well.
